workspace "CYNX-AI Architecture" "Project-level architecture generated by Barkly Docs." {
    model {
        project = softwareSystem "CYNX-AI" "System analyzed by Barkly Docs." {
            ai = container "ai" "Top-level project area. 15 source file(s); 136 indexed code element(s)." "Software"
            benchmark = container "benchmark" "Top-level project area. 35 source file(s); 117 indexed code element(s)." "Software"
            hardware = container "hardware" "Top-level project area. 38 source file(s); 387 indexed code element(s)." "Software"
            interfaces = container "interfaces" "Top-level project area. 5 source file(s); 17 indexed code element(s)." "Software"
            memory = container "memory" "Top-level project area. 4 source file(s); 18 indexed code element(s)." "Software"
            Project_root = container "Project root" "Top-level project area. 10 source file(s); 100 indexed code element(s)." "Software"
            scripts = container "scripts" "Top-level project area. 1 source file(s); 2 indexed code element(s)." "Software"
            tests = container "tests" "Top-level project area. 8 source file(s); 32 indexed code element(s)." "Software"
            tools = container "tools" "Top-level project area. 11 source file(s); 112 indexed code element(s)." "Software"
            voice = container "voice" "Top-level project area. 6 source file(s); 26 indexed code element(s)." "Software"
        }
        project.Project_root -> project.ai "connects to (18) — calls, imports"
        project.Project_root -> project.benchmark "connects to (12) — calls, contains"
        project.Project_root -> project.hardware "connects to (99) — calls, contains, imports"
        project.Project_root -> project.interfaces "connects to (1) — imports"
        project.Project_root -> project.memory "connects to (4) — imports"
        project.Project_root -> project.tools "connects to (4) — calls"
        project.ai -> project.interfaces "connects to (107) — calls"
        project.ai -> project.memory "connects to (2) — calls"
        project.benchmark -> project.Project_root "connects to (1) — calls"
        project.benchmark -> project.ai "connects to (11) — calls, imports"
        project.benchmark -> project.hardware "connects to (10) — calls, contains, imports"
        project.benchmark -> project.memory "connects to (2) — imports"
        project.benchmark -> project.tests "connects to (2) — calls"
        project.benchmark -> project.tools "connects to (3) — calls"
        project.hardware -> project.ai "connects to (14) — calls, imports"
        project.hardware -> project.interfaces "connects to (11) — calls, contains"
        project.hardware -> project.memory "connects to (1) — imports"
        project.memory -> project.ai "connects to (1) — contains"
        project.scripts -> project.interfaces "connects to (1) — imports"
        project.tests -> project.ai "connects to (50) — calls, imports"
        project.tests -> project.hardware "connects to (6) — imports"
        project.tests -> project.memory "connects to (4) — imports"
        project.tests -> project.voice "connects to (2) — calls"
        project.tools -> project.hardware "connects to (19) — calls, imports"
    }
    views {
        container project "project-overview" "Project-level component dependencies" {
            include *
            autolayout lr
        }
        styles {
            element "Software System" { background #171117 color #FFD5E6 stroke #FF6B9D }
            element "Container" { shape RoundedBox background #2A1B27 color #FFD5E6 stroke #FF6B9D }
            relationship { color #7DFFB2 routing Orthogonal }
        }
    }
}
